FROM python:3.8

WORKDIR /app

# 复制 Python 依赖文件
COPY requirements.txt .

# 安装依赖
RUN pip install -r requirements.txt

# 复制 Python 源代码
COPY ./flask-backend /app

# 创建必要的目录
RUN mkdir -p /app/attack_results \
    /app/attack_scripts \
    /app/test_dataset \
    /app/train_dataset \
    /app/user_models

# 设置环境变量
ENV IS_DOCKER=true

# 暴露端口
EXPOSE 5000

# 启动命令
CMD ["python", "main.py"]